package dev.acacia.job_trucker.offer;

public enum OffStep {
    OFERTA_REGISTRADA,
    ENVIADO_CV,
    CONTACTO_RECIBIDO,
    ENTREVISTA,
    PRUEBA_TECNICA,
    CONTRATO_OFERTADO,
    CONTRATO_ACEPTADO,
    CONTRATO_RECHAZADO,
    FEEDBACK_RECIBIDO,
    CANDIDATURA_RECHAZADA
}
